#!/bin/bash
# Get the containing directory.
DOTS=$(cd "$(dirname "$0")" && pwd -P)

# Symlink the rc files.
for f in "$DOTS"/*rc; do
  ln -s "$f" $HOME/.$(basename "$f")
done

# Make folders for linking into.
mkdir -p "$HOME/.config/git"

# Symlink the remaining files.
ln -s "$DOTS"/gitconfig "$HOME/.gitconfig"
ln -s "$DOTS"/.gitignore "$HOME/.config/git/ignore"

# Check if running under zsh.
if [ "$SHELL" != "/bin/zsh" ]; then
  if [ -x "/bin/zsh" ]; then
    read -e -n 1 -p 'Change shell to zsh (y/N)? ' ZSH
    if [ "$ZSH" == 'y' ]; then
      chsh -s /bin/zsh
    fi
  fi
fi

# Check if running on OSX.
if [ "$(uname -s)" == 'Darwin' ]; then
  if ! type brew 2>/dev/null; then
    # Optionally install Homebrew.
    read -e -n 1 -p 'Install Homebrew (y/N)? ' BREW
    if [ "$BREW" == 'y' ]; then
      ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
  fi
fi

GOPATH="/usr/local/go"
if [ ! -d "$GOPATH" ]; then
  read -e -n 1 -p 'Create $GOPATH (y/N)? ' GO
  if [ "$GO" == 'y' ]; then
    mkdir -p "$GOPATH/src/github.com"
    ln -s "$HOME/Documents" "$GOPATH/src/github.com/$USER"
  fi
fi

# Currently not auto installing packages:
# brew install homebrew/dupes/screen nethack ripgrep
