#!/bin/sh
# Get the containing directory.
DOTS=$(cd "$(dirname "$0")" && pwd -P)

# Symlink the rc files.
for f in "$DOTS"/*rc; do
  ln -s "$f" $HOME/.$(basename "$f")
done

# Make folders for linking into.
mkdir -p "$HOME/.config/git"

# Symlink the remaining files.
ln -s "$DOTS"/gitconfig "$HOME/.config/git/config"
ln -s "$DOTS"/.gitignore "$HOME/.config/git/ignore"
